---
# tasks file for samba-configure
- name: Update APT cache
  ansible.builtin.apt:
    update_cache: true
    cache_valid_time: 3600
  when: ansible_os_family == "Debian"

- name: Ensure samba is installed
  ansible.builtin.package:
    name:
      - samba
    state: present

- name: Ensure smbd service is started and enabled
  ansible.builtin.service:
    name: smbd
    state: started
    enabled: true

- name: Ensure samba user group exists
  ansible.builtin.group:
    name: "{{ samba_user }}"
    gid: "{{ samba_usergid }}"
    state: present

- name: Ensure samba user exists
  ansible.builtin.user:
    name: "{{ samba_user }}"
    group: "{{ samba_user }}"
    uid: "{{ samba_useruid }}"
    create_home: false
    shell: /usr/sbin/nologin
    state: present

- name: Copy smb config to remote
  ansible.builtin.template:
    src: smb.conf.j2
    dest: /etc/samba/smb.conf
    mode: "0664"
  notify: Restart smbd

- name: Ensure smb password is set
  ansible.builtin.shell: "(echo {{ samba_password }}; echo {{ samba_password }}) | smbpasswd -s -a {{ samba_user }}"
  register: smbpasswd
  changed_when: "'Added user sambauser' in smbpasswd.stdout"
